# Makefile.deps created Tue Nov 26 02:03:45 PST 2013
debug.o: debug.c debug.h
stack.o: stack.c stack.h bigint.h debug.h
bigint.o: bigint.c bigint.h debug.h
token.o: token.c token.h debug.h
main.o: main.c bigint.h debug.h stack.h token.h
